### ISSUE TITLE
move to revenge?

### ISSUE THREAD

**Issue by Cristiandis** [daisuke1227/BunnyUpdates#2]
need help with the revenge tweak, if you could join the revenge discord server and help i would really appreciate it

**Comment by Cristiandis** [comment]
@daisuke1227

**Comment by daisuke1227** [comment]
Sure of course I’ll join :3

**Comment by Cristiandis** [comment]
> Sure of course I’ll join :3

https://discord.gg/jtUbg9Nc
om already maintaining updated builds myself and discordnotrack, but some help will be very much accepted
